services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tsarka_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=Asia/Almaty
